version: "3"

services:
  nats-ws:
    build:
      dockerfile: Dockerfile
    ports:
      - "4222:4222" # 4222 for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "8443:8443" # for websocket
